export interface IProdutoDto {
  nome: string,
  tipo: string,
  precoDeVenda: number,
  marca: string,
  unidade: string,
  producao: string,
  itensPorCaixa: number,
  dataDeValidade: Date,
  gtin : string,
  gtinTributario: string,
  descricao: string,
  //
  estoqueMinimo: number,
  estoqueMaximo: number,
  diasCrossdocking: number,
  // //
  pesoLiquido: number,
  pesoBruto: number,
  largura: number,
  comprimento: number,
  altura: number,
  unidadeTamanho: string,
  // //
  origem: string,
  ncm: string,
  cest: string,
  tipoItem: string,
  aliquotaTributo: number,
  icmsBaseRetencao: number,
  icmsStBaseRetencao: number,
  icmsProprio: number,
  pisFixo: number,
  cofinsFixo: number,
}
